name: CI

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Test Action
      uses: ./
      with:
        directory: .test
        snakefile: .test/Snakefile
        args: "--cores 1"

    - name: Test containerize commmand
      uses: ./
      with:
        directory: .test
        snakefile: .test/Snakefile
        args: "--cores 1"
        containerize: true
      
    - name: Show Content
      run: |
        ls -alh
  
    - name: Show Dockerfile
      run: |
        cat Dockerfile
